<?php
    define("ILLINOIS","http://www.blackhorsecarriers.com/illinoislocations.php?site=1200+North+Kirk,Batavia,Il+60510&locname=Batavia");
    define("ARIZONA","http://www.blackhorsecarriers.com/arizonalocations.php?site=4932+W+Colter,+Gelendale,AZ+85401&locname=Glendale");
    define("INDIANA","http://www.blackhorsecarriers.com/indianalocations.php?site=15000B+Highway+41+North,Evansville,IN+47725&locname=Evansville");
    define("MINNESOTA","http://www.blackhorsecarriers.com/minnesotalocations.php?site=3500+Southwest+Blvd,Chaska,MN+43123&locname=Chaska");
    define("OHIO","http://www.blackhorsecarriers.com/ohiolocations.php?site=3500+Southwest+Blvd,Grove%20City,OH+43123&locname=Grove%20City");
    define("VIRGINIA","http://www.blackhorsecarriers.com/virginialocations.php?site=821+Fiber+Plant+Rd,Riverville,VA+24553&locname=Riverville");
    define("MARYLAND","http://www.blackhorsecarriers.com/marylandlocations.php?site=8751+Gas+House+Pike,Frederick,MD+21701&locname=Frederick");
    define("NEWYORK","http://www.blackhorsecarriers.com/newyorklocations.php?site=300+State+Route+281,Tully,NY+13159&locname=Tully");
    define("PENNSYLVANIA","http://www.blackhorsecarriers.com/pennsylvanialocations.php?site=2700+Saucon+Valley+Road,Center%20Valley,PA+18034&locname=Center%20Valley");
    define("WISCONSIN","http://www.blackhorsecarriers.com/wisconsinlocations.php?site=5521+88th+Avenue,Kenosha,WI+53141&locname=Kenosha");
    define("FLORIDA","http://www.blackhorsecarriers.com/floridalocations.php?site=13470+International+Parkway,Jacksonville,FL+32218&locname=Jacksonville");
?>
